id: workspace
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest: 
    version: v1beta1
    id: workspace
    containers:
      - name: workspace
        image: 185.39.216.131:5000/francois/workspace:0.1.3
        cpu: 100
        #privileged: true
        ports:
          - containerPort: 22
            hostPort: 22
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
    volumes:
      - name: docker-socket
        source:
          {hostDir: {path: /var/run/docker.sock}}
labels: 
  name: workspace
  ssh: on
