id: workspace
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest: 
    version: v1beta1
    id: workspace
    containers:
      - name: workspace
        image: francois/k8s-workspace:0.1.1
        cpu: 100
        #privileged: true
        ports:
          - containerPort: 22
            hostPort: 2222
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
          - name: host-share
            mountPath: /root/shares
    volumes:
      - name: docker-socket
        source:
          {hostDir: {path: /var/run/docker.sock}}
      - name: host-share
        source:
          {hostDir: {path: /opt/shares/workspace}}
labels: 
  name: workspace
  service: ssh
