id: db-keystone
kind: Pod
apiVersion: v1beta1
desiredState: 
  manifest:
    version: v1beta1
    id: db-keystone
    containers:
      - name: master
        image: francois/db-keystone:0.1.0
        cpu: 100
        ports:
          containerPort: 3306
          hostPort: 3306
labels:
  name: db-keystone
  type: db
